version: '3.8'

services:   
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    networks:
      - chatbotnetwork

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
      - "80:80"
    depends_on:
      - server
    networks:
      - chatbotnetwork

volumes:
  db_data:

networks:
  chatbotnetwork:
    driver: bridge
